- ibrdtn/daemon/src/core/EventDispatcher.h
- ibrdtn/daemon/src/routing/prophet/ProphetRoutingExtension.cpp
These patches may improve the performance by permitting to process events of the same type in parallel. Further, there is a patch which should solve a ring dependency which could lead to a dead-lock in environments with many nodes and a lot of traffic.
> Ring lock and performance

- ibrcommon/ibrcommon/data/BloomFilter.cpp
- ibrcommon/ibrcommon/data/BloomFilter.h
- ibrcommon/tests/unittests/BloomFilterTest.cpp
- ibrdtn/daemon/src/storage/SQLiteBundleSet.cpp
- ibrdtn/daemon/tests/unittests/BundleSetTest.cpp
- ibrdtn/daemon/tests/unittests/BundleSetTest.hh
- ibrdtn/ibrdtn/ibrdtn/data/MemoryBundleSet.cpp
This patch-set solves #142 but may also break downward compatibility since there is a bug in version 1.0.0 that may crash the daemon on receiving a Bloom-filter with a different size.
> Add grow-able Bloom-filters

- ibrcommon/ibrcommon/data/BloomFilter.cpp
- ibrcommon/ibrcommon/data/BloomFilter.h
- ibrcommon/tests/unittests/BloomFilterTest.cpp
- ibrcommon/tests/unittests/BloomFilterTest.hh
- ibrdtn/daemon/src/storage/SQLiteBundleSet.cpp
- ibrdtn/ibrdtn/ibrdtn/data/MemoryBundleSet.cpp
For better estimation of the memory consumption, the parameters of
the constructor are now in byte instead of bits. The filter may grow up to
the maximum size depending on the estimated allocation.
> Add maximum table size to Bloom-filter class

- ibrdtn/tools/src/dtninbox.cpp
- ibrdtn/tools/src/dtnoutbox.cpp
- ibrdtn/tools/src/dtntrigger.cpp
The processes called by dtntrigger are no longer called with parameters for source and
data file. Instead, environment variables contain source, destination, proc. flags,
lifetime, time-stamp and sequence-number. That approach allows to specify individual
command parameters for each dtntrigger instance. Further, the payload of the bundle is
passed via standard input instead of using a temporary file and the dtntrigger instance
supports to get daemonized if libdaemon is linked.
> Improved dtntrigger

- ibrdtn/daemon/src/api/Registration.cpp
- ibrdtn/ibrdtn/configure.ac
- ibrdtn/ibrdtn/ibrdtn/data/EID.cpp
- ibrdtn/ibrdtn/ibrdtn/data/EID.h
The match() support of EIDs allows to use regular expressions as endpoint identifiers.
Using this capability applications are able to match wildcard endpoints. E.g. an application
registered to "app/\(.*\)" can receive bundles address to dtn://node/app/foo as well as
dtn://node/app/bar.
> Regex endpoints

- ibrdtn/daemon/src/core/filter/SecurityFilter.cpp
Without BSP support we can not execute any security check. Therefore, we always
proceed as if the check were successful and return with the positive action.
> daemon: Disable security checks if the daemon was compiled without BSP support

- ibrdtn/daemon/src/routing/RetransmissionExtension.cpp
Prior this patch there exist erase operations without locking. Since
these operations are triggered by events, a lock is required to not
collide with concurrent operations.
> daemon: Add missing lock for the retransmission set

- ibrdtn/daemon/src/storage/MemoryBundleStorage.cpp
- ibrdtn/daemon/tests/unittests/BundleStorageTest.cpp
- ibrdtn/daemon/tests/unittests/BundleStorageTest.hh
By exploiting the ordered set of bundles, the
search can be aborted earlier if the bundle does not
exist in the storage.
> daemon: Optimize get() in MemoryBundleStorage

- android/ibrdtn/res/values-de/strings.xml
- android/ibrdtn/res/values/strings.xml
- android/ibrdtn/src/de/tubs/ibr/dtn/daemon/Preferences.java
- android/ibrdtn/src/de/tubs/ibr/dtn/service/DaemonProcess.java
- android/ibrdtn/src/de/tubs/ibr/dtn/service/DaemonStorageUtils.java
The logfile, bundles, and temporary files are no longer
stored in "/sdcard/ibrdtn". Instead the logfiles are stored
in the Download directory on the external media. Bundles
are placed within the private folder on the external
media and temporary files (BLOBs) are stored in the
internal app cache directory.
> android-daemon: Store bundles in private storage

- android/ShareBox/src/de/tubs/ibr/dtn/sharebox/data/Utils.java
- android/Talkie/src/de/tubs/ibr/dtn/dtalkie/service/RecorderService.java
- android/Talkie/src/de/tubs/ibr/dtn/dtalkie/service/TalkieService.java
- android/Talkie/src/de/tubs/ibr/dtn/dtalkie/service/Utils.java
Talkie now used the internal app storage to store audio files.
ShareBox now stores its files in the public download folder on
the external media.
> Android remove separate app folder

- ibrcommon/ibrcommon/data/BLOB.cpp
- ibrdtn/daemon/src/storage/SQLiteBundleStorage.cpp
If the open() method of file-based BLOBs fails, the resources allocated within the semaphore is never released. This patch fixes this issue.
> Fix handling of semaphore for file resources

- ibrcommon/ibrcommon/Iterator.h
- ibrdtn/daemon/etc/ibrdtnd.conf
- ibrdtn/daemon/src/Configuration.cpp
- ibrdtn/daemon/src/Configuration.h
- ibrdtn/daemon/src/NativeDaemon.cpp
- ibrdtn/daemon/src/routing/prophet/DeliveryPredictabilityMap.cpp
- ibrdtn/daemon/src/routing/prophet/DeliveryPredictabilityMap.h
- ibrdtn/daemon/src/routing/prophet/ProphetRoutingExtension.cpp
- ibrdtn/daemon/src/routing/prophet/ProphetRoutingExtension.h
Push notifications are now only sent if the option is set within the configuration to yes and if new routes found. Disappearing endpoints no longer issue a notification.
> Make push notification of PRoPHET routing optional

- ibrdtn/daemon/src/routing/prophet/ForwardingStrategy.cpp
- ibrdtn/daemon/src/routing/prophet/ForwardingStrategy.h
- ibrdtn/daemon/src/routing/prophet/ProphetRoutingExtension.cpp
Now PRoPHET routing forwards a broadcast packet if the backwards route
is known by the peer OR at least the local routing knows a backwards
route.
> daemon: PRoPHET broadcast routing optimization

- ibrdtn/daemon/src/routing/prophet/ForwardingStrategy.cpp
The previous version of the check combined the local with the peer
check. If the local check failed due to an exception the peer check
was not performed. Now the peer check if performed even if the local
check fails.
> daemon: Split backroute check in PRoPHET

- ibrdtn/daemon/etc/ibrdtnd.conf
- ibrdtn/daemon/src/Configuration.cpp
- ibrdtn/daemon/src/Configuration.h
- ibrdtn/daemon/src/core/BundleCore.cpp
- ibrdtn/daemon/src/core/BundleCore.h
- ibrdtn/daemon/src/routing/NeighborRoutingExtension.cpp
- ibrdtn/daemon/src/routing/NodeHandshake.cpp
- ibrdtn/daemon/src/routing/NodeHandshake.h
- ibrdtn/daemon/src/routing/NodeHandshakeExtension.cpp
- ibrdtn/daemon/src/routing/StaticRoutingExtension.cpp
- ibrdtn/daemon/src/routing/epidemic/EpidemicRoutingExtension.cpp
- ibrdtn/daemon/src/routing/flooding/FloodRoutingExtension.cpp
- ibrdtn/daemon/src/routing/prophet/ProphetRoutingExtension.cpp
- ibrdtn/daemon/tests/unittests/ConfigurationTest.cpp
- ibrdtn/daemon/tests/unittests/ConfigurationTest.hh
Routing limitations specifies forwarding limits for block sizes or if foreign bundles or non-singleton bundles are accepted. With this patch-set, these limitations are exchanged using the routing handshake. A peer will checks bundles to transfer against the limitations before sending them out. This reduces the number of aborted transmissions in case of limitations.
The limitations are still configured using the configuration file. Related options are listed below.
```
limit_blocksize = <size-in-bytes>
limit_foreign_blocksize = <size-in-bytes>
routing_forwarding = <yes|no>
routing_accept_nonsingleton = <yes|no>
```
The scope of the option *routing_forwarding* has been reduced to singleton bundles. The acceptance of non-singleton bundles are configured with the new option …
> Routing Limitations

- .travis.yml
- ibrcommon/tests/net/tcpstreamtest.cpp
- ibrdtn/ibrdtn/tests/net/TestStreamConnection.cpp
In unit-tests IPv6 loopback addresses were used to test server and client components locally. This is no longer supported on testing infrastructure of Travis CI. Therefore the dependency is removed within this change-set.
> Remove IPv6 dependency from unit testing

- ibrdtn/daemon/src/core/BundleCore.cpp
- ibrdtn/ibrdtn/ibrdtn/data/EID.cpp
- ibrdtn/ibrdtn/tests/data/TestEID.cpp
The application part of endpoint identifiers in IPN scheme is mandatory and
must be always added to the string representation even if the application
part is set to zero / not set.
Closes #206.
> Always show the application part in IPN endpoint identifiers

- ibrdtn/daemon/src/api/ExtendedApiHandler.cpp
If a bundle is sent via 'bundle sent', the response now also includes
the unique information of a bundle (timestamp, sequence number, and
source endpoint identifier).
> daemon: Return bundle ID after bundle is sent via plain-text API

- ibrdtn/ibrdtn/ibrdtn/data/EID.cpp
- ibrdtn/ibrdtn/ibrdtn/data/EID.h
Due to the introduction of a pointer (_regex) to the member variables of EID, it now needs a dedicated copy constructor to ensure correct destruction of objects duplicated, e. g., by a return-by-value.
This is especially important when returning EID instances in STL collections such as in the Registration class here: https://github.com/ibrdtn/ibrdtn/blob/master/ibrdtn/daemon/src/api/Registration.cpp#L162 where the copy constructor will be used frequently and would wrongly just copy the address stored in pointer _regex of EID.
This also fixes issue #214 .
Correct handling of _regex is solved in the copy constructor by calling EID::prepare() if the other instance's _regex pointer is not NULL, of course feel free to adapt the patch if this is wrong.
> Fix: EID needs copy constructor since it maintains a pointer

- ibrdtn/daemon/src/api/EventConnection.cpp
- ibrdtn/daemon/src/api/EventConnection.h
The EventConnection now returns BundlePurgeEvent and BundleExpiredEvent.
> daemon: Extended EventConnection by purge and expired event

- android/app/build.gradle
I ran into the problem that my path to Android NDK was not set during build (since it was only defined in ~/.bashrc like mentioned in the [wiki](https://github.com/ibrdtn/ibrdtn/wiki/Build-IBR-DTN-for-Android)). Now the NDK path is also taken from the local.properties if available.
This could also be achieved by setting the path in the correct configuration file for sh/dash but using the path from the project settings looks more intuitive to me.
> Add NDK path from local.properties to gradle build file

- ibrdtn/daemon/src/core/FragmentManager.cpp
The FragmentManager does not inject merged bundles correctly. See [https://github.com/ibrdtn/ibrdtn/issues/218](url) for details.
> changed injection of merged bundles to be treated as non-local

- ibrcommon/ibrcommon/net/socket.cpp
- ibrcommon/ibrcommon/net/vaddress.cpp
Hi, I discovered this subtle bug while testing IBR-DTN in an ad-hoc network with nodes configured only with IPv6 Link-Local addresses. The IPND works well and nodes discover each other. But while trying to send some data, for example using the dtnping tool, a TCPConnection failed error pops up (I use the TCP-CL). Looking at code I saw that Link-Local addresses are supported including the scope-id, so I started to debug with gdb. The problem is that the "getaddrinfo" call fails because "address" variable is pointing to a non valid memory location containing garabage. This variable (and "service" variable too) is defined as C style char array and is pointing to the address of the char array obtained calling std::string::c_str method on the temporary std::string object returned by …
> Fix temporary strings causing getaddrinfo to fail

- ibrcommon/ibrcommon/net/vinterface.cpp
- ibrdtn/daemon/src/Configuration.cpp
- ibrdtn/daemon/src/net/DiscoveryAgent.cpp
- ibrdtn/daemon/src/net/DiscoveryAgent.h
- ibrdtn/daemon/src/net/IPNDAgent.cpp
If not defined, the 'any' interface is now default for all convergence-layers. This also changes the
default behavior of dtnd. Previously, the daemon comes up without any interface. Now, the default is to bind to <any> and create a TCP-CL instance.
```
$ dtnd
Sat Oct 14 15:14:58 2017 INFO NativeDaemon: IBR-DTN daemon 1.0.1 (build a171900)
Sat Oct 14 15:14:58 2017 INFO Configuration: Using default settings. Call with --help for options.
Sat Oct 14 15:14:58 2017 INFO NativeDaemon: Parallel event processing enabled using 4 processes.
Sat Oct 14 15:14:58 2017 INFO BundleCore: Local node name: dtn://link
Sat Oct 14 15:14:58 2017 INFO BundleCore: Forwarding of bundles enabled.
Sat Oct 14 15:14:58 2017 INFO BundleCore: Non-singleton bundles are accepted.
Sat Oct 14 15:14:58 2017 INFO …
```
> Set <any> interface as default

- ibrcommon/ibrcommon/net/socket.cpp
- ibrcommon/ibrcommon/net/socket.h
- ibrdtn/daemon/src/net/IPNDAgent.cpp
- ibrdtn/daemon/src/net/IPNDAgent.h
Now sockets bound to 0.0.0.0 and ::/0 are always created for receiving multicast packets. For sending message over specific interfaces, a socket with a random port is created for each address of used interfaces.
> Multicast binding of IPNDAgent refactored

- ibrcommon/ibrcommon/net/socket.h
"The `backlog` argument defines the maximum length to which the queue
of pending connections for sockfd may grow.  If a connection request
arrives when the queue is full, the client may receive an error with
an indication of ECONNREFUSED or, if the underlying protocol supports
retransmission, the request may be ignored so that a later reattempt
at connection succeeds."
Default value of 0 results in the test hanging undefinetely on one of
my boxes (linux-4.12.12, glibc-2.23) (looks like requests ignored as
described above). I'm not sure how no one has hit this before but it
took me like 6 hours to find out what's wrong with select().
Changing backlog argument to 2 on listen resolved the issue
immediately. I suggest this as a reasonable default.
`tcpserversocket` seems to be used in tests …
> Fix for tcpstreamtest::baseTest hanging on select

- ibrcommon/tests/ssl/CipherStreamTest.cpp
- ibrdtn/daemon/src/Configuration.h
- ibrdtn/daemon/src/net/TCPConnection.h
- ibrdtn/daemon/src/storage/DataStorage.h
- ibrdtn/tools/src/dtntunnel.cpp
- missing header for stand alone complitation,
- error: stack frame size of >60kb in functions
'TUN2BundleGateway::process' [-Werror,-Wframe-larger-than=]
'TUN2BundleGateway::received' [-Werror,-Wframe-larger-than=]
'CipherStreamTest::aesstream_test01' [-Werror,-Wframe-larger-than=]
- some classes have virtual functions but non-virtual destructor [-Werror,-Wnon-virtual-dtor].
> Resolving build issues for some platforms

- .travis.yml
Trusty env should have 2 CPUs.
> Enabling compilation in parallel for Travis

- .travis.yml
- ibrdtn/README
- ibrdtn/configure-dev
- ibrdtn/daemon/tests/Makefile.am
- ibrdtn/tools/configure.ac
More dependencies added to cover more code during build.
> Improve Travis CI tests

- ibrdtn/daemon/src/net/DatagramConvergenceLayer.cpp
- ibrdtn/daemon/src/net/DatagramConvergenceLayer.h
std::list.erase(it) invalidates the iterator, the following call to delete results in segfault.
http://kera.name/articles/2011/06/iterator-invalidation-rules/
Also touching method signature, pointer is preferred for a view. This is also in line with the existing LOWPANConvergenceLayer.getConnection().
> Fixing segfault on delete in DatagramConvergenceLayer

- ibrdtn/tools/src/dtntunnel.cpp
As long as the guidelines are limited to C++ features of C++03,
the data() function of std::vector is not available.
> Revert changes towards C++11

- ibrdtn/daemon/tests/unittests/FakeDatagramService.cpp
DatagramClTest::queueTest line 108 references msg.data[0] which causes
'std::out_of_range' exception where msg.data.size() is 0.
DatagramClTest::queueTestterminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
> Fixing DatagramClTest::queueTest test

- ibrcommon/configure.ac
- ibrdtn/daemon/configure.ac
- ibrdtn/ibrdtn/configure.ac
- ibrdtn/tools/configure.ac
Fixes issue #242.
W/o enable-debug:
g++ -DHAVE_CONFIG_H -I.. -O2 -MT SyslogStream.lo -MD -MP -MF .deps/SyslogStream.Tpo -c -o SyslogStream.lo SyslogStream.cpp
With enable-debug:
g++ -DHAVE_CONFIG_H -I.. -ggdb -g3 -O0 -Wall -Wextra -pedantic -Wconversion -D__DEVELOPMENT_ASSERTIONS__ -MT SyslogStream.lo -MD -MP -MF .deps/SyslogStream.Tpo -c -o SyslogStream.lo SyslogStream.cpp
> Making enable-debug to turn optimizations off

- ibrdtn/daemon/src/security/exchange/DHProtocol.cpp
- ibrdtn/daemon/src/security/exchange/Makefile.am
- ibrdtn/daemon/src/security/exchange/openssl_compat.cpp
- ibrdtn/daemon/src/security/exchange/openssl_compat.h
This patch adds compatibility with openssl 1.1.0 to ibrdtnd.
Signed-off-by: Eneas U de Queiroz <cote2004-github@yahoo.com>
> ibrdtnd: added openssl 1.1 compatibility
